# Generated by Django 6.0.5 on 2026-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="roll",
            field=models.BigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
